<?php

/**
 * @file
 * Contains answer2_1.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function answer2_1_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the answer2_1 module.
    case 'help.page.answer2_1':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function answer2_1_theme() {
  return [
    'answer2_1' => [
      'render element' => 'children',
    ],
  ];
}
